name: Windows Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # If there are no NuGet packages, this step is harmless
      - name: Restore (NuGet)
        run: nuget restore "Video Encode 2.sln" || echo "no packages to restore"

      - name: Build x64 Release
        run: msbuild "Video Encode 2.sln" /p:Configuration=Release /p:Platform=x64 /m

      - name: Collect exes
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path dist -Force | Out-Null
          Get-ChildItem -Recurse -Path "Video Encode 2" -Include *.exe -File |
            Where-Object { $_.FullName -match "x64\\Release" } |
            Copy-Item -Destination dist
          Get-ChildItem dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*
          if-no-files-found: error
