name: Windows Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # --- Install vcpkg in a known path and integrate with MSBuild ---
      - name: Install vcpkg
        shell: pwsh
        run: |
          $Env:VCPKG_ROOT = "$env:RUNNER_TEMP\vcpkg"
          git clone https://github.com/microsoft/vcpkg $Env:VCPKG_ROOT
          cmd /c "$Env:VCPKG_ROOT\bootstrap-vcpkg.bat -disableMetrics"
          & "$Env:VCPKG_ROOT\vcpkg.exe" integrate install
          "VCPKG_ROOT=$Env:VCPKG_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append

      # --- Install OpenCV for x64 (needed by the project) ---
      - name: Install OpenCV (x64)
        shell: pwsh
        run: |
          & "$env:VCPKG_ROOT\vcpkg.exe" install opencv:x64-windows

      # If you eventually need lodepng via vcpkg, uncomment:
      # - name: Install lodepng
      #   shell: pwsh
      #   run: |
      #     & "$env:VCPKG_ROOT\vcpkg.exe" install lodepng:x64-windows

      # --- Build the solution in Release|x64 ---
      - name: Build x64 Release
        run: msbuild "Video Encode 2.sln" /p:Configuration=Release /p:Platform=x64 /m

      # --- Collect built EXEs from x64\Release ---
      - name: Collect exes
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path dist -Force | Out-Null
          Get-ChildItem -Recurse -Path "Video Encode 2" -Include *.exe -File |
            Where-Object { $_.FullName -match "x64\\Release" } |
            Copy-Item -Destination dist
          Get-ChildItem dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*
          if-no-files-found: error
